version: '3.7'
services:
  datathonbuild: 
    build:
        context: ./
        dockerfile: ./docker/builder/Dockerfile
  angular:
    build:
      context: ./
      dockerfile: ./docker/angular/Dockerfile
  nest:
    build:
      context: ./
      dockerfile: ./docker/nest/Dockerfile
    ports:
      - 8080:8080
