version: '3.7'
services:
  datathonbuild: 
    build:
        context: ./
        dockerfile: ./docker/builder/Dockerfile
  angular:
    build:
      context: ./
      dockerfile: ./docker/angular/Dockerfile
    ports:
      - '4200:4200'
  nest:
    build:
      context: ./
      dockerfile: ./docker/nest/Dockerfile
    ports:
      - '3333:3333'
